name: Test and Build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: pip install -r src/requirements.txt
    - name: Check linting
      working-directory: src
      run: ruff check .
    - name: Test with pytest
      working-directory: src
      run: pytest tests.py
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/nacar7701-crypto/ci-cd:latest
    
