name: Test and Build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: pip install -r scr/requirements.txt
    - name: Test with pytest
      run: pytest tests.py
